# -*- coding: utf-8 -*-
"""proyek_data_mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2EQKLF2BB2jAz7f1gQD9tC7-ITfyicS
"""

# Import Library

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

df = pd.read_csv("/content/cleaned_sales.csv")

print("Shape awal:", df.shape)
df.head()

print(df.head())
print(df.info())
print(df.describe())
print(df.isna().sum())

df.isnull().sum()

df['Qty'].value_counts().head()

df['Price'].skew(), df['Amount Price Item'].skew()

df[['Price', 'Amount Price Item']].quantile([0.25, 0.5, 0.75, 0.9, 0.99])

df = df[(df['Price'] > 0) & (df['Amount Price Item'] > 0)]
print("Setelah hapus harga 0:", df.shape)

def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    low = Q1 - 1.5 * IQR
    high = Q3 + 1.5 * IQR
    return data[(data[column] >= low) & (data[column] <= high)]

df = remove_outliers_iqr(df, 'Price')
df = remove_outliers_iqr(df, 'Amount Price Item')

print("Setelah outlier removal:", df.shape)

df = df.dropna(subset=['Item Name', 'Qty', 'Amount Price Item'])

df_group = df.groupby(['Item Name']).agg({
    'Qty': 'sum',
    'Amount Price Item': 'sum',
    'Invoice Number': 'nunique'
}).reset_index()

df_group.rename(columns={
    'Qty': 'Total_Quantity',
    'Amount Price Item': 'Total_Revenue',
    'Invoice Number': 'Sales_Frequency'
}, inplace=True)

df_group['Avg_Revenue_Per_Transaction'] = df_group['Total_Revenue'] / df_group['Sales_Frequency']

total_revenue_all = df_group['Total_Revenue'].sum()
df_group['Revenue_Share'] = df_group['Total_Revenue'] / total_revenue_all

df_group['Total_Revenue_Log'] = np.log1p(df_group['Total_Revenue'])
df_group['Total_Quantity_Log'] = np.log1p(df_group['Total_Quantity'])
df_group['Avg_Revenue_Log'] = np.log1p(df_group['Avg_Revenue_Per_Transaction'])

features = df_group[['Total_Quantity_Log',
                     'Total_Revenue_Log',
                     'Sales_Frequency',
                     'Avg_Revenue_Log']]

scaler = StandardScaler()
scaled = scaler.fit_transform(features)

df_scaled = pd.DataFrame(scaled, columns=features.columns)

inertia = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(df_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(K_range, inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("Jumlah Cluster (k)")
plt.ylabel("Inertia")
plt.show()

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    clusters = kmeans.fit_predict(df_scaled)
    sil = silhouette_score(df_scaled, clusters)
    print(f"k={k}, silhouette={sil}")

kmeans = KMeans(n_clusters=4, random_state=42)
df_group['Cluster'] = kmeans.fit_predict(df_scaled)

print(df_group['Cluster'].value_counts())

cluster_0 = df_group[df_group['Cluster'] == 0]
cluster_1 = df_group[df_group['Cluster'] == 1]
cluster_2 = df_group[df_group['Cluster'] == 2]
cluster_3 = df_group[df_group['Cluster'] == 3]

print("=== Cluster 0 (Low Performer) ===")
display(cluster_0[['Item Name','Total_Quantity','Total_Revenue','Sales_Frequency']])

print("\n=== Cluster 1 (Medium Performer) ===")
display(cluster_1[['Item Name','Total_Quantity','Total_Revenue','Sales_Frequency']])

print("\n=== Cluster 2 (High Performer) ===")
display(cluster_2[['Item Name','Total_Quantity','Total_Revenue','Sales_Frequency']])

print("\n=== Cluster 3 (Top Performer) ===")
display(cluster_3[['Item Name','Total_Quantity','Total_Revenue','Sales_Frequency']])

plt.scatter(df_group['Total_Revenue'], df_group['Total_Quantity'],
            c=df_group['Cluster'], cmap='viridis')

plt.xlabel("Total Revenue")
plt.ylabel("Total Quantity")
plt.title("Cluster Visualization")
plt.show()

df_group.to_excel("hasil_cluster_produk.xlsx", index=False)

import pandas as pd

# Load hasil clustering
df = pd.read_excel("hasil_cluster_produk.xlsx")

# Pastikan cluster berupa angka
df['Cluster'] = df['Cluster'].astype(int)

# Loop untuk setiap cluster
for c in sorted(df['Cluster'].unique()):
    print(f"\n=== Top 5 Produk Cluster {c} ===")

    # Urutkan per revenue tertinggi
    top5 = df[df['Cluster'] == c].sort_values(
        by="Total_Revenue", ascending=False
    ).head(5)

    display(top5[['Item Name', 'Total_Quantity', 'Total_Revenue', 'Sales_Frequency']])

label_map = {
    0: "Medium Performer",
    1: "Top Performer",
    2: "High Performer",
    3: "Low Performer"
}

for c in sorted(df['Cluster'].unique()):
    label = label_map.get(c, f"Cluster {c}")
    print(f"\n=== Top 5 Produk {label} (Cluster {c}) ===")

    top5 = df[df['Cluster'] == c].sort_values(
        by="Total_Revenue", ascending=False
    ).head(5)

    display(top5[['Item Name', 'Total_Quantity', 'Total_Revenue', 'Sales_Frequency']])

import pandas as pd
import matplotlib.pyplot as plt

# ============================================
# LOAD DATA
# ============================================
df = pd.read_excel("hasil_cluster_produk.xlsx")

# Pastikan cluster berupa integer
df['Cluster'] = df['Cluster'].astype(int)

# ============================================
# 1. PIE CHART DISTRIBUSI PRODUK PER CLUSTER
# ============================================

plt.figure(figsize=(7,7))
cluster_counts = df['Cluster'].value_counts().sort_index()

plt.pie(cluster_counts,
        labels=[f"Cluster {c}" for c in cluster_counts.index],
        autopct='%1.1f%%',
        startangle=90)

plt.title("Distribusi Jumlah Produk per Cluster")
plt.tight_layout()
plt.show()


# ============================================
# 2. TOP 5 PRODUK PER CLUSTER (BAR CHART)
# ============================================

clusters = sorted(df['Cluster'].unique())

for c in clusters:
    top5 = df[df['Cluster'] == c].sort_values(
        by="Total_Revenue", ascending=False
    ).head(5)

    # --- BAR CHART Revenue ---
    plt.figure(figsize=(10,4))
    plt.bar(top5["Item Name"], top5["Total_Revenue"])
    plt.xticks(rotation=45, ha='right')
    plt.title(f"Top 5 Produk Berdasarkan Revenue - Cluster {c}")
    plt.xlabel("Item Name")
    plt.ylabel("Total Revenue")
    plt.tight_layout()
    plt.show()

    # --- BAR CHART Quantity ---
    plt.figure(figsize=(10,4))
    plt.bar(top5["Item Name"], top5["Total_Quantity"])
    plt.xticks(rotation=45, ha='right')
    plt.title(f"Top 5 Produk Berdasarkan Quantity - Cluster {c}")
    plt.xlabel("Item Name")
    plt.ylabel("Total Quantity")
    plt.tight_layout()
    plt.show()

    # --- BAR CHART Sales Frequency ---
    plt.figure(figsize=(10,4))
    plt.bar(top5["Item Name"], top5["Sales_Frequency"])
    plt.xticks(rotation=45, ha='right')
    plt.title(f"Top 5 Produk Berdasarkan Sales Frequency - Cluster {c}")
    plt.xlabel("Item Name")
    plt.ylabel("Sales Frequency")
    plt.tight_layout()
    plt.show()

